# Generated by Django 4.0.6 on 2022-09-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_varations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='varations',
            new_name='variations',
        ),
    ]
