# Generated by Django 4.0.6 on 2022-10-06 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount_id',
            new_name='amount_paid',
        ),
    ]
